name: Cache

on:
  workflow_call:
    inputs:
      run:
        required: true
        type: string
    outputs:
      cache-hit:
        value: ${{ jobs.cache.outputs.cache-hit }}
      key:
        value: ${{ jobs.cache.outputs.key }}

jobs:
  cache:
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache.outputs.cache-hit }}
      key: ${{ env.key }}
    steps:
      - name: Get key
        run: |
          echo "key=$(${{ inputs.run }})" >> $GITHUB_ENV
          touch ~/.cache

      - name: Cache
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.cache
          key: ${{ env.key }}