# Compare the two files to see if they are the same
name: Compare

on:
  workflow_call:
    inputs:
      new:
        required: true
        type: string
      commit_message:
        default: 'feat: bump VERSION to'
        required: false
        type: string
    outputs:
      changed:
        value: ${{ jobs.cmp.outputs.changed }}
      version:
        value: ${{ jobs.cmp.outputs.version }}

jobs:
  cmp:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.cmp.outputs.changed }}
      version: ${{ steps.cmp.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Compare
        id: cmp
        run: |
          echo "${{ inputs.new }}" > NEWVERSION
          
          if cmp -s VERSION NEWVERSION; then
            echo "No change!"
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "version=" >> $GITHUB_OUTPUT
          else
            mv NEWVERSION VERSION
            echo "Changed!"
            echo "The new version is: $(cat VERSION)"
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT
          fi
