name: Git

on:
  workflow_call:
    inputs:
      run:
        required: true
        type: string
      commit_message:
        required: true
        type: string
      commit_author:
        default: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
        required: false
        type: string
      tagging_message:
        required: false
        type: string
    
jobs:
  git:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare
        run: ${{ inputs.run }}

      - name: Git
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ${{ inputs.commit_message }}
          commit_author: ${{ inputs.commit_author }}
          tagging_message: ${{ inputs.tagging_message }}
